#!/bin/sh

mac=`ifconfig eth0 | grep HWaddr | awk '{print tolower($NF)}'| sed 's|:|-|g'`

# When installing, the default route will be via the gateway assigned by the dhcp server - typically the dhcp server itself, typically 10.0.0.1

tftp_server_ip=`ip route | grep default | awk '{print $3}'`

# Grab network configuration file if there
atftp $tftp_server_ip -g -r /ubuntu/config/$mac/01-netcfg.yaml -l 01-netcfg.yaml

if [ -s "01-netcfg.yaml" ]; then
	# Public address
	IP_ADDRESS=`grep 'addresses: \[.*/.*\]' 01-netcfg.yaml | grep -v '\[10\.' | sed 's|^.*: \[||' | sed 's|/.*$||'`
	# 10.0 address
	IP_ADDRESS_PRIVATE=`grep 'addresses: \[.*/.*\]' 01-netcfg.yaml | grep '\[10\.' | sed 's|^.*: \[||' | sed 's|/.*$||'`
	HOSTNAME_FQ=`host $IP_ADDRESS | awk '{print $NF}'`
	HOSTNAME=`echo $HOSTNAME_FQ | sed 's|\..*$||g'`
else
	echo "No network configuration available via TFTP, using fallback, assuming one network card."
	echo "Please check /etc/netplan/01-netcfg.yaml and disable network configuration in /etc/rc.local"
	atftp $tftp_server_ip -g -r /ubuntu/config/fallback/01-netcfg.yaml -l 01-netcfg.yaml
	
	MY_INTERNAL_IP_NUM=`ifconfig | grep 'inet ' | grep -v 127 | head -1 | awk '{print $2}' | awk -F. '{print $NF}'`
	HOSTNAME=peon${MY_INTERNAL_IP_NUM}
	
	cat <<"EOF">> /mnt/etc/rc.local
#!/bin/bash

if [ $(grep eth0 /etc/netplan/01-netcfg.yaml) ]; then

	LOCAL_NIC=`ip link | grep ' UP ' | awk -F : '{print $2}' | sed -E 's|^ +||' | while read name; do ls -ld /sys/class/net/$name 2>/dev/null | ( grep -v virtual >&/dev/null ) && echo $name; done | head -1`
	if [ -n "$LOCAL_NIC" ]; then
		sed -i "s|eth0|$LOCAL_NIC|" /etc/netplan/01-netcfg.yaml
	netplan apply
	fi

fi

EOF

	chmod +x /mnt/etc/rc.local
fi

mv 01-netcfg.yaml "/mnt/etc/netplan/"

echo $HOSTNAME > /mnt/etc/hostname

# Copy over customfiles/install

cp -af /install/* /mnt/

