#!/bin/bash

########################
### Set variables
########################
SCRIPTDIR=$( dirname -- "$0"; )
. "$SCRIPTDIR/set_params"
########################

$CHROOT $INSTALL_DIR

# This will be mounted onto /var/lib/postgresql in the db pod
mkdir -p /usr/local/postgresql

# We back it up to sciencedata every night

mkdir -p /root/.config/rclone

cat <<EOF > /root/.config/rclone/rclone.conf
[sciencedata-storage-cloud]
type = webdav
url = https://sciencedata.dk
vendor = other
user = cloud
pass = W4nxg78ibFW3IKJbiHs_AHWvXwnJxsMFEnWw
EOF

cat <<EOF > /usr/local/sbin/zenodo_backup.sh
#!/bin/bash
# Remove the db container
kubectl scale --replicas=0 deployment/db
rclone sync --transfers 1 /usr/local/postgresql sciencedata-storage-cloud:zenodo/postgresql
# Fire up the db container again
kubectl scale --replicas=1 deployment/db
EOF

cat <<EOF > /etc/cron.daily/zenodo
/usr/local/sbin/zenodo_backup.sh
EOF

# Cronjob to point zenodo to the lb pod

cat <<EOF > /usr/local/sbin/zenodo_host.sh
#!/bin/bash

lbip=`kubectl get services -o wide | grep -E '^lb ' | awk '{print $3}'`

grep "$lbip" /etc/hosts >&/dev/null || sed -i -E "s|^[0-9\.]+\s+(zenodo)|$lbip\t\1|" /etc/hosts
grep "$lbip" /etc/hosts >&/dev/null || sed -i -E "s|^<none>\s+(zenodo)|$lbip\t\1|" /etc/hosts

EOF

cat <<EOF > /etc/cron.hourly/zenodo
/usr/local/bin/zenodo_host.sh
EOF

# Cronjob to point pgadmin to the pgadmin pod

cat <<EOF > /usr/local/sbin/pgadmin_host.sh
#!/bin/bash

lbip=`kubectl get pods -o wide | grep -E '^pgadmin ' | awk '{print $6}'`

grep "$lbip" /etc/hosts >&/dev/null || sed -i -E "s|^[0-9\.]+\s+(pgadmin)|$lbip\t\1|" /etc/hosts
grep "$lbip" /etc/hosts >&/dev/null || sed -i -E "s|^<none>\s+(pgadmin)|$lbip\t\1|" /etc/hosts

EOF

cat <<EOF > /etc/cron.hourly/pgadmin
/usr/local/bin/pgadmin_host.sh
EOF


chmod +x /usr/local/sbin/zenodo_host.sh /etc/cron.hourly/zenodo /usr/local/sbin/zenodo_backup.sh \
/etc/cron.daily/zenodo /usr/local/bin/pgadmin_host.sh /etc/cron.hourly/pgadmin

# Caddy needs to be able to update root CA
cat <<EOF >> /etc/sudoers
# Caddy needs this to update /usr/local/share/ca-certificates/
caddy	ALL=NOPASSWD:ALL
EOF

mkdir /etc/caddy

cat <<EOF > /etc/caddy/sites/sciencerepository.caddy
########################
### sciencerepository
########################

http://sciencerepository.sciencedata.dk {
	redir https://sciencerepository.dk{uri}
}

http://sciencerepository.dk {
	redir https://sciencerepository.dk{uri}
}

https://sciencerepository.sciencedata.dk {
	redir https://sciencerepository.dk{uri}
}

http://repository.dk {
	redir https://sciencerepository.dk{uri}
}

https://repository.sciencedata.dk {
	header content-security-policy "connect-src 'self' https://sciencedata.dk https://*.sciencedata.dk"
	header -referrer-policy
	header -x-frame-options
	header -strict-transport-security
	reverse_proxy {
	transport http {
			tls_insecure_skip_verify
		}
		to https://zenodo
	}
	log {
		output file /var/log/zenodo.log
	}
}

https://sciencerepository.dk {
	reverse_proxy {
	transport http {
			tls_insecure_skip_verify
		}
		to https://zenodo
	}
	log {
		output file /var/log/zenodo.log
	}
}

########################
### pgadmin
### (for sciencerepository)
########################

https://kube.sciencedata.dk:9443 {
	reverse_proxy {
		to http://pgadmin:80
	}
	log {
		output file /var/log/caddy/pgadmin.log
	}
	encode gzip zstd
	php_fastcgi unix//run/php/php7.4-fpm.sock
	@blocked not remote_ip 130.225.245.245 87.73.109.19
	respond @blocked "Nope" 403
}
EOF

## Fill in email and password, start pgadmin pod with kubectl apply -f /root/pgadmin.yaml,
## then visit https://kube.sciencedata.dk:9443/login and set DB host to "db", database to "zenodo", db user and password to "zenodo"

cat <<EOF > /root/pgadmin.yaml
apiVersion: v1
kind: Pod
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  containers:
  - name: pgadmin
    image: dpage/pgadmin4
    env:
    - name: PGADMIN_DEFAULT_EMAIL
      value: ""
    - name: PGADMIN_DEFAULT_PASSWORD
      value: ""
    ports:
      - containerPort: 80
EOF

touch /var/log/zenodo.log
touch /var/log/nbviewer.log
touch /var/log/pgadmin.log
touch /var/log/caddy.log

chown caddy /var/log/zenodo.log /var/log/nbviewer.log /var/log/pgadmin.log /var/log/caddy.log

# Set up GitHub credentials
atftp $ADMIN_IP -g -r /freebsd/config/private/github_credentials.sh -l github_credentials.sh
. ./github_credentials.sh
rm github_credentials.sh

cat <<EOF >> "/root/.netrc"
machine github.com
login $GITHUB_USERNAME
password $GITHUB_PASSWORD
EOF

# Get the Zenodo YAML files
git clone https://github.com/deic-dk/zenodo_deployment.git

###################
## Fire up the pods
###################

kubectl apply -f zenodo_deployment/zenodo_volumes.yaml
kubectl apply -f zenodo_deployment/zenodo_support_services.yaml
kubectl apply -f zenodo_deployment/zenodo_services.yaml

