#!/bin/bash

kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml

cat <<EOF | kubectl apply -f -
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: kube-public
EOF

cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: kube-public
EOF

## Forward port via ssh from a terminal on the host you're running your browser on
# ssh -L 8001:localhost:8001 root@kube.sciencedata.dk

## Run this on another terminal on kube.sciencedata.dk
# kubectl proxy --address='127.0.0.1' --accept-hosts='^.*$'

## Get token with
# kubectl -n kube-public describe secret `kubectl -n kube-public get secret | grep admin-user | awk '{print $1}'`

## Paste it into the dashboard web interface on
# http://127.0.0.1:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/
