#!/bin/bash

curl -LO https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb
dpkg -i cvmfs-release-latest_all.deb
apt update
apt install cvmfs

cvmfs_config setup
service autofs reload
echo "CVMFS_REPOSITORIES=atlas.cern.ch,atlas-condb.cern.ch,grid.cern.ch,unpacked.cern.ch,sft.cern.ch" > /etc/cvmfs/default.local
echo "CVMFS_CLIENT_PROFILE=single" >> /etc/cvmfs/default.local
