#!/bin/bash

########################
### Set variables
########################
SCRIPTDIR=$( dirname -- "$0"; )
. "$SCRIPTDIR/set_params"
########################


# Mathematica and MATLAB are grabbed from the admin server.
# These will be mounted as local partitions in the pods.

mkdir -p $INSTALL_DIR/usr/local/software

echo "Getting tarballs. This may take a while..."
atftp $ADMIN_IP -g -l $INSTALL_DIR//usr/local/software/WolframEngine.tar.gz -r /kubernetes/WolframEngine.tar.gz
atftp $ADMIN_IP -g -l $INSTALL_DIR/usr/local/software/matlab.tar.gz -r /kubernetes/matlab.tar.gz
echo "Unpacking..."
tar -xzf $INSTALL_DIR/usr/local/software/WolframEngine.tar.gz -C $INSTALL_DIR/usr/local/software/
tar -xzf $INSTALL_DIR/usr/local/software/matlab.tar.gz -C $INSTALL_DIR/usr/local/software/
rm $INSTALL_DIR/usr/local/software/WolframEngine.tar.gz
rm $INSTALL_DIR/usr/local/software/matlab.tar.gz
