#!/bin/bash

########################
### Set variables
########################
SCRIPTDIR=$( dirname -- "$0"; )
. "$SCRIPTDIR/set_params"
########################

########################
### Deploy pdf_sign_sciencedata
########################

# Write YAML

ls $INSTALL_DIR/root/pdf_sign.yaml >&/dev/null || \
cat <<EOF > $INSTALL_DIR/root/pdf_sign.yaml
apiVersion: v1
kind: Service
metadata:
  name: pdfsign
  labels:
    app: x509
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    x509-service-name: pdfsign
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    x509-service-name: pdfsign
  name: pdfsign
spec:
  replicas: 1
  selector:
    matchLabels:
      x509-service-name: pdfsign
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        x509-service-name: pdfsign
        domain:
        user: cloud
    spec:
      securityContext:
        fsGroupChangePolicy: Always
      imagePullSecrets:
      - name: regcred
      containers:
      - args:
        env:
        - name: USERNAME
          value: "www"
        image: sciencedata/pdf_sign_sciencedata:latest
        imagePullPolicy: "Always"
        name: pdfsign
        securityContext:
          capabilities:
            add: ["SYS_CHROOT"] 
        ports:
        - containerPort: 80
          protocol: TCP
      restartPolicy: Always
      #nodeName: peon145
---
EOF

# Deploy the service
$CHROOT $INSTALL_DIR kubectl apply -f pdf_sign.yaml

# Script and cronjob to point pdfsign to the pdf_sign_sciencedata pod
ls $INSTALL_DIR/usr/local/sbin/pdfsign_host.sh >&/dev/null || \
cat <<"EOF" > $INSTALL_DIR/usr/local/sbin/pdfsign_host.sh
#!/bin/bash

lbip=`get_containers cloud 2>/dev/null | grep -E '\|pdfsign\|' | awk -F \| '{print $4}'`

if [ -z "$lbip" ]; then
  exit 1
fi

grep "$lbip" /etc/hosts >&/dev/null || sed -i -E "s|^[0-9\.]+\s+(pdfsign)|$lbip\t\1|" /etc/hosts
grep "pdfsign" /etc/hosts >&/dev/null || echo "$lbip  pdfsign" >> /etc/hosts
EOF

ls $INSTALL_DIR/etc/cron.hourly/pdfsign >&/dev/null || \
cat <<EOF > $INSTALL_DIR/etc/cron.hourly/pdfsign_host
/usr/local/sbin/pdfsign_host.sh
EOF

chmod +x $INSTALL_DIR/usr/local/sbin/pdfsign_host.sh $INSTALL_DIR/etc/cron.hourly/pdfsign_host

########################
### caddy configuration
########################

# We're assuming a running caddy has already been configured.
ls $INSTALL_DIR/etc/caddy/sites || mkdir $INSTALL_DIR/etc/caddy/sites
ls $INSTALL_DIR/etc/caddy/sites/pdfsign.caddy >&/dev/null || \
cat <<EOF > $INSTALL_DIR/etc/caddy/sites/pdfsign.caddy
### pdfsign ###

https://10.0.0.12:7443 {
  reverse_proxy {
    to http://pdfsign:80
  }
  log {
    output file /var/log/caddy/pdfsign.log
  }
}

EOF

