#!/bin/bash

chroot /mnt

# We're assuming a Caddyfile has already been created, i.e. this should run after install_zenodo_support
cat <<EOF >> /etc/caddy/Caddyfile

https://kube.sciencedata.dk:8443 {
	reverse_proxy {
		to http://nbviewer:8080
	}
	log {
		output file /var/log/nbviewer.log
	}
}

https://10.0.0.12:8443 {
        reverse_proxy {
                to http://nbviewer:8080
        }
        log {
                output file /var/log/nbviewer.log
        }
}

EOF
