#!/bin/bash

# Install base system
debootstrap --arch amd64 focal /mnt http://dk.archive.ubuntu.com/ubuntu
mount -t proc none /mnt/proc
mount -o bind /dev /mnt/dev

# Configure locale
chroot /mnt apt-get install locales
chroot /mnt dpkg-reconfigure locales

# Configure keyboard
chroot /mnt apt-get install console-data
chroot /mnt dpkg-reconfigure console-data

# Install the kernel
#apt-cache search linux-image
chroot /mnt apt-get install linux-image-4.9.0-3-amd64

cat <<EOF>> /mnt/etc/network/interfaces
auto lo
iface lo inet loopback

allow-hotplug eth0
iface eth0 inet dhcp
EOF

# Install grub
chroot /mnt apt-get install grub2
chroot /mnt grub-install /dev/sda
chroot /mnt update-grub
