#!/bin/bash

chroot /mnt

# We're assuming a Caddyfile has already been created, i.e. this should run after install_zenodo_support
cat <<EOF >> /etc/caddy/Caddyfile

https://kube.sciencedata.dk:8443 {
	reverse_proxy {
		to http://nbviewer:8080
	}
	log {
		output file /var/log/nbviewer.log
	}
}

https://10.0.0.12:8443 {
        reverse_proxy {
                to http://nbviewer:8080
        }
        log {
                output file /var/log/nbviewer.log
        }
}

http://sciencenotebooks.sciencedata.dk {
	redir https://sciencenotebooks.dk{uri}
}

http://sciencenotebooks.dk {
	redir https://sciencenotebooks.dk{uri}
}

https://sciencenotebooks.sciencedata.dk {
	redir https://sciencenotebooks.dk{uri}
}

https://sciencenotebooks.dk {
        reverse_proxy {
                to http://nbviewer:8080
        }
        log {
                output file /var/log/nbviewer.log
        }
}

EOF

# Cronjob to point nbviewer to the nbviewer pod

cat <<EOF > /usr/local/sbin/nbviewer_host.sh
#!/bin/bash
nbip=`kubectl get services -o wide | grep -E '^nbviewer ' | awk '{print $3}'`
grep "$nbip" /etc/hosts >&/dev/null || sed -i -E "s|^[0-9\.]+\s+(nbviewer)|$lbip\t\1|" /etc/hostss
EOF

cat <<EOF > /etc/cron.hourly/nbviewer
/usr/local/bin/nbviewer_host.sh
EOF

grep nbviewer /etc/hosts || echo "10.108.30.107	nbviewer" >> /etc/hosts

