#!/bin/bash

export SCRIPTDIR=$( dirname -- "$0"; )

export ADMIN_IP=10.0.0.1

# Set this to get an entry in /etc/hosts
#export SCIENCEDATA_INTERNAL_IP=10.0.0.13

# Check if we're already in chroot
if [ "$(stat -c %d:%i /)" != "$(stat -c %d:%i /proc/1/root/.)" ]; then
	echo "We are already chrooted - probably being called from another install script."
	export IN_CHROOT=1
else
	# Check if we're being called from mfslinux
	if [ -e /usr/libexec/linuxinstall ] && grep /mnt /proc/mounts >& /dev/null; then
		echo "We're called manually from mfslinux and will chroot"
		export INSTALL_DIR=/mnt
		export CHROOT=chroot
	else
		echo "We're called manually on an installed system. NOT chroot'ing"
		$CHROOT $INSTALL_DIR timedatectl set-timezone Europe/Copenhagen
	fi
fi

export MY_HOSTNAME=`cat $INSTALL_DIR/etc/hostname`

# If this box has a static IP, grab the internal IP from the netplan config
export MY_INTERNAL_IP=`cat /etc/netplan/01-netcfg.yaml | yq -r '.network.ethernets | map_values(select(.addresses[0] | startswith("10.0.0."))) | to_entries | .[0].value.addresses[0]' | sed -r 's|/[0-9]+$||'`
# Otherwise assume one network interface
if [ -z "$MY_INTERNAL_IP" ]; then
	export MY_INTERNAL_IP=`ifconfig | grep 'inet ' | grep -v 127 | head -1 | awk '{print $2}' | sed -E 's|:.*$||'`
fi

export MY_INTERNAL_IP_NUM=`echo $MY_INTERNAL_IP | sed -E 's|10\.0\.[0-9]+\.||'`

# Figure out the active network interface

# First try to grab interface assigned 10.0. address from netplan config file

# This only works if the network is actually up
#ip_num=`ip addr | grep 'inet 10.0.0' | awk '{print $2}' | sed 's|10\.0\.0\.||'`
#LOCAL_NIC=`ip route | grep 10.0.0.0/24 | awk '{print $3}'`

LOCAL_NIC=`cat /etc/netplan/01-netcfg.yaml | yq -r '.network.ethernets | map_values(select(.addresses[0] | startswith("10.0."))) | to_entries | .[0].key'`
# If not there,  grab first interface
if [ -z "$LOCAL_NIC" ]; then
	LOCAL_NIC=`cat /etc/netplan/01-netcfg.yaml | yq -r '.network.ethernets | to_entries | .[0].key'`
fi
# If netplan is not used, take the first interface that's up
if [ -z "$LOCAL_NIC" ]; then
	LOCAL_NIC=`ip link | grep ' UP ' | awk -F : '{print $2}' | sed -E 's|^ +||' | while read name; do ls -ld /sys/class/net/$name 2>/dev/null | ( grep -v virtual >&/dev/null ) && echo $name; done | head -1`
fi

